{{- if .Values.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: hivemind-secrets
  namespace: {{ .Values.operatorNamespace }}
  labels:
    app.kubernetes.io/name: hivemind
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.githubToken | quote }}
{{- end }}
